import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class MessierService {

  constructor(private http: HttpClient) { }

  getObjects(): Observable<any> {
    return of([
      {
          "id": "M1",
          "messierKind": "Planetary Nebula",
          "size": "6 x 4",
          "magnitude": 8.4,
          "rightAscension": 334.5,
          "declination": 1321,
          "constellation": "Taurus",
          "season": "Winter",
          "remarks": "Crab nebula",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M1_crab.html"
      },
      {
          "id": "M2",
          "messierKind": "Globular Star Cluster",
          "size": "8.2",
          "magnitude": 6.3,
          "rightAscension": 1293.5,
          "declination": -50,
          "constellation": "Aquarius",
          "season": "Autumn",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M2.html"
      },
      {
          "id": "M3",
          "messierKind": "Globular Star Cluster",
          "size": "19",
          "magnitude": 6.4,
          "rightAscension": 822.2,
          "declination": 1703,
          "constellation": "Canes Venatici",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M3_globular_cluster.html"
      },
      {
          "id": "M4",
          "messierKind": "Globular Star Cluster",
          "size": "14",
          "magnitude": 6.4,
          "rightAscension": 983.7,
          "declination": 1591,
          "constellation": "Scorpius",
          "season": "Summer",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M4.html"
      },
      {
          "id": "M5",
          "messierKind": "Globular Star Cluster",
          "size": "12.7",
          "magnitude": 6.2,
          "rightAscension": 918.5,
          "declination": 125,
          "constellation": "Serpens",
          "season": "Summer",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M5.html"
      },
      {
          "id": "M6",
          "messierKind": "Open Star Cluster",
          "size": "25",
          "magnitude": 5.3,
          "rightAscension": 1060.1,
          "declination": -1933,
          "constellation": "Scorpius",
          "season": "Summer",
          "remarks": "Butterfly cluster",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M6_butterfly_cluster.html"
      },
      {
          "id": "M7",
          "messierKind": "Open Star Cluster",
          "size": "60",
          "magnitude": 3.2,
          "rightAscension": 1073.9,
          "declination": -2089,
          "constellation": "Scorpius",
          "season": "Summer",
          "remarks": "Ptolemy's cluster",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M7.html"
      },
      {
          "id": "M8",
          "messierKind": "Diffused Nebula",
          "size": "60 x 35",
          "magnitude": 6,
          "rightAscension": 1083.2,
          "declination": -1463,
          "constellation": "Sagittarius",
          "season": "Summer",
          "remarks": "Lagoon nebula",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M8.html"
      },
      {
          "id": "M9",
          "messierKind": "Globular Star Cluster",
          "size": "6",
          "magnitude": 7.3,
          "rightAscension": 1039.1,
          "declination": -1111,
          "constellation": "Ophiuchus",
          "season": "Summer",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M9.html"
      },
      {
          "id": "M10",
          "messierKind": "Globular Star Cluster",
          "size": "8.2",
          "magnitude": 6.7,
          "rightAscension": 1017.1,
          "declination": -247,
          "constellation": "Ophiuchus",
          "season": "Summer",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M10.html"
      },
      {
          "id": "M11",
          "messierKind": "Open Star Cluster",
          "size": "10",
          "magnitude": 6.3,
          "rightAscension": 1131.1,
          "declination": -376,
          "constellation": "Sculptor",
          "season": "Summer",
          "remarks": "Wild duck cluster",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M11_wild_duck_cluster.html"
      },
      {
          "id": "M12",
          "messierKind": "Globular Star Cluster",
          "size": "9.3",
          "magnitude": 6.6,
          "rightAscension": 1007.2,
          "declination": -117,
          "constellation": "Ophiuchus",
          "season": "Summer",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M12.html"
      },
      {
          "id": "M13",
          "messierKind": "Globular Star Cluster",
          "size": "10",
          "magnitude": 5.7,
          "rightAscension": 1001.7,
          "declination": 2187,
          "constellation": "Hercules",
          "season": "Summer",
          "remarks": "The Hercules cluster",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M13_hercules_globular_cluster.html"
      },
      {
          "id": "M14",
          "messierKind": "Globular Star Cluster",
          "size": "3",
          "magnitude": 7.7,
          "rightAscension": 1057.6,
          "declination": -195,
          "constellation": "Ophiuchus",
          "season": "Summer",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M14.html"
      },
      {
          "id": "M15",
          "messierKind": "Globular Star Cluster",
          "size": "7.4",
          "magnitude": 6,
          "rightAscension": 1290,
          "declination": 730,
          "constellation": "Pegasus",
          "season": "Autumn",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M15_globular_cluster.html"
      },
      {
          "id": "M16",
          "messierKind": "Diffused Nebula",
          "size": "35 x 28",
          "magnitude": 6.4,
          "rightAscension": 1098.8,
          "declination": -827,
          "constellation": "Serpens",
          "season": "Summer",
          "remarks": "Eagle nebula",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M16_eagle_nebula.html"
      },
      {
          "id": "M17",
          "messierKind": "Diffused Nebula",
          "size": "46 x 37",
          "magnitude": 7,
          "rightAscension": 1100.8,
          "declination": -971,
          "constellation": "Sagittarius",
          "season": "Summer",
          "remarks": "Omega nebula",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M17_omega_nebula.html"
      },
      {
          "id": "M18",
          "messierKind": "Open Star Cluster",
          "size": "9",
          "magnitude": 7.5,
          "rightAscension": 1099.9,
          "declination": -1028,
          "constellation": "Sagittarius",
          "season": "Summer",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M18.html"
      },
      {
          "id": "M19",
          "messierKind": "Globular Star Cluster",
          "size": "4.3",
          "magnitude": 6.6,
          "rightAscension": 1022.6,
          "declination": -1575,
          "constellation": "Ophiuchus",
          "season": "Summer",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M19.html"
      },
      {
          "id": "M20",
          "messierKind": "Diffused Nebula",
          "size": "29 x 27",
          "magnitude": 9,
          "rightAscension": 1081.9,
          "declination": -1382,
          "constellation": "Sagittarius",
          "season": "Summer",
          "remarks": "Trifid nebula",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M20_trifid_nebula.html"
      },
      {
          "id": "M21",
          "messierKind": "Open Star Cluster",
          "size": "10",
          "magnitude": 6.5,
          "rightAscension": 1084.7,
          "declination": -1350,
          "constellation": "Sagittarius",
          "season": "Summer",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M21.html"
      },
      {
          "id": "M22",
          "messierKind": "Globular Star Cluster",
          "size": "17.3",
          "magnitude": 5.9,
          "rightAscension": 1116.4,
          "declination": -1435,
          "constellation": "Sagittarius",
          "season": "Summer",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M22.html"
      },
      {
          "id": "M23",
          "messierKind": "Open Star Cluster",
          "size": "25",
          "magnitude": 6.9,
          "rightAscension": 1076.9,
          "declination": -1141,
          "constellation": "Sagittarius",
          "season": "Summer",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M23.html"
      },
      {
          "id": "M24",
          "messierKind": "Star Cloud",
          "size": "90",
          "magnitude": 4.6,
          "rightAscension": 1098.4,
          "declination": -1105,
          "constellation": "Sagittarius",
          "season": "Summer",
          "remarks": "Star cloud",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M24_sagittarius_star_cloud.html"
      },
      {
          "id": "M25",
          "messierKind": "Open Star Cluster",
          "size": "40",
          "magnitude": 6.5,
          "rightAscension": 1111.7,
          "declination": -1155,
          "constellation": "Sagittarius",
          "season": "Summer",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M25.html"
      },
      {
          "id": "M26",
          "messierKind": "Open Star Cluster",
          "size": "9",
          "magnitude": 9.3,
          "rightAscension": 1125.3,
          "declination": -564,
          "constellation": "Sculptor",
          "season": "Summer",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M26.html"
      },
      {
          "id": "M27",
          "messierKind": "Planetary Nebula",
          "size": "8 x 4",
          "magnitude": 7.6,
          "rightAscension": 1199.6,
          "declination": 1363,
          "constellation": "Vulpecula",
          "season": "Summer",
          "remarks": "Dumb-bell nebula",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M27_planetary_nebula.html"
      },
      {
          "id": "M28",
          "messierKind": "Globular Star Cluster",
          "size": "4.7",
          "magnitude": 7.3,
          "rightAscension": 1104.6,
          "declination": -1492,
          "constellation": "Sagittarius",
          "season": "Summer",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M28.html"
      },
      {
          "id": "M29",
          "messierKind": "Open Star Cluster",
          "size": "12",
          "magnitude": 7.1,
          "rightAscension": 1223.9,
          "declination": 2312,
          "constellation": "Cygnus",
          "season": "Summer",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M29.html"
      },
      {
          "id": "M30",
          "messierKind": "Globular Star Cluster",
          "size": "5.7",
          "magnitude": 8.4,
          "rightAscension": 1300.3,
          "declination": -1391,
          "constellation": "Capricornus",
          "season": "Autumn",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M30_globular_cluster.html"
      },
      {
          "id": "M31",
          "messierKind": "Galaxy",
          "size": "109 x 62",
          "magnitude": 4.8,
          "rightAscension": 42.7,
          "declination": 2476,
          "constellation": "Andromeda",
          "season": "Autumn",
          "remarks": "Andromeda galaxy",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M31_andromeda.html"
      },
      {
          "id": "M32",
          "messierKind": "Galaxy",
          "size": "8.7 x 6.5",
          "magnitude": 8.7,
          "rightAscension": 42.7,
          "declination": 2452,
          "constellation": "Andromeda",
          "season": "Autumn",
          "remarks": "Satellite galaxy of M31",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M32_dwarf_elliptical_galaxy.html"
      },
      {
          "id": "M33",
          "messierKind": "Galaxy",
          "size": "70.8 x 41.7",
          "magnitude": 6.7,
          "rightAscension": 93.8,
          "declination": 1839,
          "constellation": "Triangulum",
          "season": "Autumn",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M33_triangulum_galaxy.html"
      },
      {
          "id": "M34",
          "messierKind": "Open Star Cluster",
          "size": "18",
          "magnitude": 5.5,
          "rightAscension": 162,
          "declination": 2567,
          "constellation": "Perseus",
          "season": "Autumn",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M34_open_cluster.html"
      },
      {
          "id": "M35",
          "messierKind": "Open Star Cluster",
          "size": "40",
          "magnitude": 5.3,
          "rightAscension": 368.9,
          "declination": 1460,
          "constellation": "Gemini",
          "season": "Winter",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M35_open_cluster.html"
      },
      {
          "id": "M36",
          "messierKind": "Open Star Cluster",
          "size": "12",
          "magnitude": 6.3,
          "rightAscension": 335.3,
          "declination": 2049,
          "constellation": "Auriga",
          "season": "Winter",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M36.html"
      },
      {
          "id": "M37",
          "messierKind": "Open Star Cluster",
          "size": "20",
          "magnitude": 6.2,
          "rightAscension": 352.4,
          "declination": 1953,
          "constellation": "Auriga",
          "season": "Winter",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M37_open_cluster.html"
      },
      {
          "id": "M38",
          "messierKind": "Open Star Cluster",
          "size": "20",
          "magnitude": 7.4,
          "rightAscension": 328.7,
          "declination": 2150,
          "constellation": "Auriga",
          "season": "Winter",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M38.html"
      },
      {
          "id": "M39",
          "messierKind": "Open Star Cluster",
          "size": "30",
          "magnitude": 5.2,
          "rightAscension": 1292.2,
          "declination": 2906,
          "constellation": "Cygnus",
          "season": "Summer",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M39.html"
      },
      {
          "id": "M40",
          "messierKind": null,
          "size": null,
          "magnitude": null,
          "rightAscension": 743.4,
          "declination": 3483,
          "constellation": "Ursa Major",
          "season": "Spring",
          "remarks": "(Unidentified)",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M40_optical_double_star.html"
      },
      {
          "id": "M41",
          "messierKind": "Open Star Cluster",
          "size": "30",
          "magnitude": 5,
          "rightAscension": 407,
          "declination": -1244,
          "constellation": "Canis Major",
          "season": "Winter",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M41.html"
      },
      {
          "id": "M42",
          "messierKind": "Diffused Nebula",
          "size": "66 x 60",
          "magnitude": 4,
          "rightAscension": 335.4,
          "declination": -323,
          "constellation": "Orion",
          "season": "Winter",
          "remarks": "The Orion nebula",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M42_orion_nebula.html"
      },
      {
          "id": "M43",
          "messierKind": "Diffused Nebula",
          "size": "20 x 15",
          "magnitude": 9,
          "rightAscension": 335.6,
          "declination": -316,
          "constellation": "Orion",
          "season": "Winter",
          "remarks": "The Orion nebula",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M43.html"
      },
      {
          "id": "M44",
          "messierKind": "Open Star Cluster",
          "size": "95",
          "magnitude": 3.7,
          "rightAscension": 520.3,
          "declination": 1189,
          "constellation": "Cancer",
          "season": "Spring",
          "remarks": "Praesepe",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M44.html"
      },
      {
          "id": "M45",
          "messierKind": "Open Star Cluster",
          "size": "100",
          "magnitude": 1.4,
          "rightAscension": 227.1,
          "declination": 1447,
          "constellation": "Taurus",
          "season": "Winter",
          "remarks": "Pleiades",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M45_pleiades.html"
      },
      {
          "id": "M46",
          "messierKind": "Open Star Cluster",
          "size": "24",
          "magnitude": 6,
          "rightAscension": 461.8,
          "declination": -889,
          "constellation": "Puppis",
          "season": "Winter",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M46.html"
      },
      {
          "id": "M47",
          "messierKind": "Open Star Cluster",
          "size": "25",
          "magnitude": 4.5,
          "rightAscension": 456.6,
          "declination": -869,
          "constellation": "Puppis",
          "season": "Winter",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M47.html"
      },
      {
          "id": "M48",
          "messierKind": "Open Star Cluster",
          "size": "30",
          "magnitude": 5.3,
          "rightAscension": 493.7,
          "declination": -347,
          "constellation": "Hydra",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M48.html"
      },
      {
          "id": "M49",
          "messierKind": "Galaxy",
          "size": "2.8 x 1.8",
          "magnitude": 8.6,
          "rightAscension": 749.7,
          "declination": 479,
          "constellation": "Virgo",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M49.html"
      },
      {
          "id": "M50",
          "messierKind": "Open Star Cluster",
          "size": "16",
          "magnitude": 6.9,
          "rightAscension": 423,
          "declination": -500,
          "constellation": "Monoceros",
          "season": "Winter",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M50.html"
      },
      {
          "id": "M51",
          "messierKind": "Galaxy",
          "size": "11.2 x 6.9",
          "magnitude": 8.1,
          "rightAscension": 809.9,
          "declination": 2832,
          "constellation": "Canes Venatici",
          "season": "Spring",
          "remarks": "Whirlpool galaxy",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M51.html"
      },
      {
          "id": "M52",
          "messierKind": "Open Star Cluster",
          "size": "12",
          "magnitude": 7.3,
          "rightAscension": 1404.2,
          "declination": 3695,
          "constellation": "Cassiopeia",
          "season": "Autumn",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M52.html"
      },
      {
          "id": "M53",
          "messierKind": "Globular Star Cluster",
          "size": "10",
          "magnitude": 7.6,
          "rightAscension": 792.9,
          "declination": 1090,
          "constellation": "Coma Berenices",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M53_globular_cluster.html"
      },
      {
          "id": "M54",
          "messierKind": "Globular Star Cluster",
          "size": "2.1",
          "magnitude": 7.3,
          "rightAscension": 1135.2,
          "declination": -1828,
          "constellation": "Sagittarius",
          "season": "Summer",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M54.html"
      },
      {
          "id": "M55",
          "messierKind": "Globular Star Cluster",
          "size": "10",
          "magnitude": 7.6,
          "rightAscension": 1180.1,
          "declination": -1856,
          "constellation": "Sagittarius",
          "season": "Summer",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M55.html"
      },
      {
          "id": "M56",
          "messierKind": "Globular Star Cluster",
          "size": "5",
          "magnitude": 8.2,
          "rightAscension": 1156.6,
          "declination": 1810,
          "constellation": "Lyra",
          "season": "Summer",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M56.html"
      },
      {
          "id": "M57",
          "messierKind": "Planetary Nebula",
          "size": "1.2 x 1",
          "magnitude": 9.3,
          "rightAscension": 1133.6,
          "declination": 1982,
          "constellation": "Lyra",
          "season": "Summer",
          "remarks": "Ring nebula",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M57_ring_nebula.html"
      },
      {
          "id": "M58",
          "messierKind": "Galaxy",
          "size": "4.4 x 3.5",
          "magnitude": 9.2,
          "rightAscension": 757.5,
          "declination": 709,
          "constellation": "Virgo",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M58.html"
      },
      {
          "id": "M59",
          "messierKind": "Galaxy",
          "size": "2.7 x 1.6",
          "magnitude": 9.6,
          "rightAscension": 762,
          "declination": 699,
          "constellation": "Virgo",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M59.html"
      },
      {
          "id": "M60",
          "messierKind": "Galaxy",
          "size": "2 x 1.8",
          "magnitude": 8.9,
          "rightAscension": 763.6,
          "declination": 693,
          "constellation": "Virgo",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M60.html"
      },
      {
          "id": "M61",
          "messierKind": "Galaxy",
          "size": "5.6 x 5.3",
          "magnitude": 10.1,
          "rightAscension": 742,
          "declination": 268,
          "constellation": "Virgo",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M61.html"
      },
      {
          "id": "M62",
          "messierKind": "Globular Star Cluster",
          "size": "4.3",
          "magnitude": 6.6,
          "rightAscension": 1021.3,
          "declination": -1807,
          "constellation": "Ophiuchus",
          "season": "Summer",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M62.html"
      },
      {
          "id": "M63",
          "messierKind": "Galaxy",
          "size": "12.6 x 7.2",
          "magnitude": 9.5,
          "rightAscension": 795.8,
          "declination": 2522,
          "constellation": "Canes Venatici",
          "season": "Spring",
          "remarks": "Sunflower galaxy",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M63.html"
      },
      {
          "id": "M64",
          "messierKind": "Galaxy",
          "size": "10 x 5.4",
          "magnitude": 8.8,
          "rightAscension": 776.8,
          "declination": 1301,
          "constellation": "Coma Berenices",
          "season": "Spring",
          "remarks": "Black-eye galaxy",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M64.html"
      },
      {
          "id": "M65",
          "messierKind": "Galaxy",
          "size": "7.8 x 1.5",
          "magnitude": 9.3,
          "rightAscension": 678.9,
          "declination": 786,
          "constellation": "Leo",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M65.html"
      },
      {
          "id": "M66",
          "messierKind": "Galaxy",
          "size": "9.1 x 4.2",
          "magnitude": 8.4,
          "rightAscension": 680.2,
          "declination": 780,
          "constellation": "Leo",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M66_spiral_galaxy.html"
      },
      {
          "id": "M67",
          "messierKind": "Open Star Cluster",
          "size": "15",
          "magnitude": 6.1,
          "rightAscension": 530.5,
          "declination": 709,
          "constellation": "Cancer",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M67.html"
      },
      {
          "id": "M68",
          "messierKind": "Globular Star Cluster",
          "size": "2.9",
          "magnitude": 8.2,
          "rightAscension": 759.5,
          "declination": -1605,
          "constellation": "Hydra",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M68.html"
      },
      {
          "id": "M69",
          "messierKind": "Globular Star Cluster",
          "size": "2.8",
          "magnitude": 8.9,
          "rightAscension": 1111.4,
          "declination": -1941,
          "constellation": "Sagittarius",
          "season": "Summer",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M69.html"
      },
      {
          "id": "M70",
          "messierKind": "Globular Star Cluster",
          "size": "2.5",
          "magnitude": 9.6,
          "rightAscension": 1123.3,
          "declination": -1938,
          "constellation": "Sagittarius",
          "season": "Summer",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M70.html"
      },
      {
          "id": "M71",
          "messierKind": "Globular Star Cluster",
          "size": "6.1",
          "magnitude": 9,
          "rightAscension": 1193.7,
          "declination": 1127,
          "constellation": "Sagitta",
          "season": "Summer",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M71.html"
      },
      {
          "id": "M72",
          "messierKind": "Globular Star Cluster",
          "size": "2",
          "magnitude": 9.8,
          "rightAscension": 1253.4,
          "declination": -753,
          "constellation": "Aquarius",
          "season": "Autumn",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M72.html"
      },
      {
          "id": "M73",
          "messierKind": "Stellar Group",
          "size": "2.8",
          "magnitude": 9,
          "rightAscension": 1259.1,
          "declination": -758,
          "constellation": "Aquarius",
          "season": "Autumn",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M73.html"
      },
      {
          "id": "M74",
          "messierKind": "Galaxy",
          "size": "10.5 x 9.5",
          "magnitude": 10.2,
          "rightAscension": 96.7,
          "declination": 947,
          "constellation": "Pisces",
          "season": "Autumn",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M74.html"
      },
      {
          "id": "M75",
          "messierKind": "Globular Star Cluster",
          "size": "1.9",
          "magnitude": 8,
          "rightAscension": 1206.1,
          "declination": -1315,
          "constellation": "Sagittarius",
          "season": "Summer",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M75.html"
      },
      {
          "id": "M76",
          "messierKind": "Planetary Nebula",
          "size": "2.5 x 1.5",
          "magnitude": 12.2,
          "rightAscension": 102,
          "declination": 3094,
          "constellation": "Perseus",
          "season": "Autumn",
          "remarks": "Little dumb-bell nebula",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M76_little_dumbbell.html"
      },
      {
          "id": "M77",
          "messierKind": "Galaxy",
          "size": "7.1 x 6.0",
          "magnitude": 8.9,
          "rightAscension": 162.7,
          "declination": -1,
          "constellation": "Cetus",
          "season": "Autumn",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M77.html"
      },
      {
          "id": "M78",
          "messierKind": "Diffused Nebula",
          "size": "8 x 6",
          "magnitude": 8.3,
          "rightAscension": 346.8,
          "declination": 3,
          "constellation": "Orion",
          "season": "Winter",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M78_reflection_nebula.html"
      },
      {
          "id": "M79",
          "messierKind": "Globular Star Cluster",
          "size": "3.2",
          "magnitude": 7.9,
          "rightAscension": 324.3,
          "declination": -1471,
          "constellation": "Lepus",
          "season": "Winter",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M79.html"
      },
      {
          "id": "M80",
          "messierKind": "Globular Star Cluster",
          "size": "3.3",
          "magnitude": 7.7,
          "rightAscension": 977.1,
          "declination": -1379,
          "constellation": "Scorpius",
          "season": "Summer",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M80.html"
      },
      {
          "id": "M81",
          "messierKind": "Galaxy",
          "size": "26.9 x 14.1",
          "magnitude": 7.9,
          "rightAscension": 595.6,
          "declination": 4144,
          "constellation": "Ursa Major",
          "season": "Spring",
          "remarks": "Bode's galaxy",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M81.html"
      },
      {
          "id": "M82",
          "messierKind": "Galaxy",
          "size": "11.2 x 4.3",
          "magnitude": 8.8,
          "rightAscension": 596,
          "declination": 4182,
          "constellation": "Ursa Major",
          "season": "Spring",
          "remarks": "Bode's galaxy",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M82.html"
      },
      {
          "id": "M83",
          "messierKind": "Galaxy",
          "size": "12.9 x 11.5",
          "magnitude": 8.2,
          "rightAscension": 817,
          "declination": -1792,
          "constellation": "Hydra",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M83_southern_pinwheel.html"
      },
      {
          "id": "M84",
          "messierKind": "Galaxy",
          "size": "6.4 x 5.6",
          "magnitude": 10,
          "rightAscension": 745,
          "declination": 773,
          "constellation": "Virgo",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M84.html"
      },
      {
          "id": "M85",
          "messierKind": "Galaxy",
          "size": "7.1 x 5.5",
          "magnitude": 10,
          "rightAscension": 745.4,
          "declination": 1091,
          "constellation": "Coma Berenices",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M85.html"
      },
      {
          "id": "M86",
          "messierKind": "Galaxy",
          "size": "8.9 x 5.8",
          "magnitude": 9.8,
          "rightAscension": 746.2,
          "declination": 776,
          "constellation": "Virgo",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M86.html"
      },
      {
          "id": "M87",
          "messierKind": "Galaxy",
          "size": "8.3 x 6.6",
          "magnitude": 9.6,
          "rightAscension": 750.8,
          "declination": 743,
          "constellation": "Virgo",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M87.html"
      },
      {
          "id": "M88",
          "messierKind": "Galaxy",
          "size": "6.9 x 3.7",
          "magnitude": 10.7,
          "rightAscension": 752,
          "declination": 865,
          "constellation": "Coma Berenices",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M88.html"
      },
      {
          "id": "M89",
          "messierKind": "Galaxy",
          "size": "5.1 x 4.7",
          "magnitude": 10.5,
          "rightAscension": 755.6,
          "declination": 753,
          "constellation": "Virgo",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M89.html"
      },
      {
          "id": "M90",
          "messierKind": "Galaxy",
          "size": "9.6 x 4.4",
          "magnitude": 10.3,
          "rightAscension": 756.8,
          "declination": 790,
          "constellation": "Virgo",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M90.html"
      },
      {
          "id": "M91",
          "messierKind": "Galaxy",
          "size": "5.4 x 4.3",
          "magnitude": 11.1,
          "rightAscension": 755.5,
          "declination": 870,
          "constellation": "Coma Berenices",
          "season": "Spring",
          "remarks": "(confused with M58?)",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M91.html"
      },
      {
          "id": "M92",
          "messierKind": "Globular Star Cluster",
          "size": "8.3",
          "magnitude": 6.1,
          "rightAscension": 1037.1,
          "declination": 2589,
          "constellation": "Hercules",
          "season": "Summer",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M92_globular_cluster.html"
      },
      {
          "id": "M93",
          "messierKind": "Open Star Cluster",
          "size": "25",
          "magnitude": 6,
          "rightAscension": 464.5,
          "declination": -1432,
          "constellation": "Puppis",
          "season": "Winter",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M93_open_cluster.html"
      },
      {
          "id": "M94",
          "messierKind": "Galaxy",
          "size": "11.2 x 9.1",
          "magnitude": 9,
          "rightAscension": 770.9,
          "declination": 2468,
          "constellation": "Canes Venatici",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M94.html"
      },
      {
          "id": "M95",
          "messierKind": "Galaxy",
          "size": "7.4 x 5.0",
          "magnitude": 10.7,
          "rightAscension": 643.9,
          "declination": 702,
          "constellation": "Leo",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M95.html"
      },
      {
          "id": "M96",
          "messierKind": "Galaxy",
          "size": "7.5 x 5.2",
          "magnitude": 9.9,
          "rightAscension": 646.7,
          "declination": 709,
          "constellation": "Leo",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M96.html"
      },
      {
          "id": "M97",
          "messierKind": "Planetary Nebula",
          "size": "3.2 x 3.2",
          "magnitude": 12,
          "rightAscension": 674.9,
          "declination": 3302,
          "constellation": "Ursa Major",
          "season": "Spring",
          "remarks": "Owl nebula",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M97_owl_nebula.html"
      },
      {
          "id": "M98",
          "messierKind": "Galaxy",
          "size": "8.4 x 1.9",
          "magnitude": 10.7,
          "rightAscension": 733.8,
          "declination": 894,
          "constellation": "Coma Berenices",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M98.html"
      },
      {
          "id": "M99",
          "messierKind": "Galaxy",
          "size": "4.6 x 3.9",
          "magnitude": 10.1,
          "rightAscension": 738.8,
          "declination": 865,
          "constellation": "Coma Berenices",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M99.html"
      },
      {
          "id": "M100",
          "messierKind": "Galaxy",
          "size": "5.3 x 4.5",
          "magnitude": 10.6,
          "rightAscension": 742.9,
          "declination": 949,
          "constellation": "Coma Berenices",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M100.html"
      },
      {
          "id": "M101",
          "messierKind": "Galaxy",
          "size": "28.8 x 26.9",
          "magnitude": 8.3,
          "rightAscension": 843.2,
          "declination": 3261,
          "constellation": "Ursa Major",
          "season": "Spring",
          "remarks": "Pinwheel nebula",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M101_pinwheel.html"
      },
      {
          "id": "M102",
          "messierKind": "Galaxy",
          "size": "2.8 x 1",
          "magnitude": 10.8,
          "rightAscension": 845.1,
          "declination": 3357,
          "constellation": "Draco",
          "season": "Summer",
          "remarks": "(confused with M101?)",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M102.html"
      },
      {
          "id": "M103",
          "messierKind": "Open Star Cluster",
          "size": "5",
          "magnitude": 7.4,
          "rightAscension": 93.2,
          "declination": 3642,
          "constellation": "Cassiopeia",
          "season": "Autumn",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M103.html"
      },
      {
          "id": "M104",
          "messierKind": "Galaxy",
          "size": "8.7 x 3.5",
          "magnitude": 8.7,
          "rightAscension": 760,
          "declination": -697,
          "constellation": "Virgo",
          "season": "Spring",
          "remarks": "Sombrero nebula",
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M104_sombrero_galaxy.html"
      },
      {
          "id": "M105",
          "messierKind": "Galaxy",
          "size": "5.3 x 4.7",
          "magnitude": 10.1,
          "rightAscension": 647.8,
          "declination": 755,
          "constellation": "Leo",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M105_elliptical_galaxy.html"
      },
      {
          "id": "M106",
          "messierKind": "Galaxy",
          "size": "19.5 x 7",
          "magnitude": 8.6,
          "rightAscension": 739,
          "declination": 2838,
          "constellation": "Canes Venatici",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M106.html"
      },
      {
          "id": "M107",
          "messierKind": "Globular Star Cluster",
          "size": "2.2",
          "magnitude": 9.2,
          "rightAscension": 992.5,
          "declination": -783,
          "constellation": "Ophiuchus",
          "season": "Summer",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M107.html"
      },
      {
          "id": "M108",
          "messierKind": "Galaxy",
          "size": "8.7 x 2.3",
          "magnitude": 10.7,
          "rightAscension": 671.6,
          "declination": 3341,
          "constellation": "Ursa Major",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M108.html"
      },
      {
          "id": "M109",
          "messierKind": "Galaxy",
          "size": "6.2 x 3.5",
          "magnitude": 10.8,
          "rightAscension": 717.6,
          "declination": 3202,
          "constellation": "Ursa Major",
          "season": "Spring",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M109.html"
      },
      {
          "id": "M110",
          "messierKind": "Galaxy",
          "size": "10 x 4.5",
          "magnitude": 9.4,
          "rightAscension": 40.3,
          "declination": 2501,
          "constellation": "Andromeda",
          "season": "Autumn",
          "remarks": null,
          "deepSkyVideo": "http://deepskyvideos.com/videos/messier/M110_galaxy.html"
      }
  ]);
  }
}
